server:
  port: 8080

spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/yijiadb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: net.sf.log4jdbc.DriverSpy